name: bgda
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black # code formatting
  - geopandas # spatial data analysis
  - nbstripout # avoid committing notebook cell outputs
  - notebook # jupyter notebook
  - pandas # data analysis
  - pyogrio # fast read/write spatial data formats
