name: bgda
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black # code formatting
  - geopandas # spatial data analysis
  - nbstripout # avoid committing notebook cell outputs
  - notebook # jupyter notebook
  - pandas # data analysis
  - pyogrio # fast read/write spatial data formats
  - pyarrow # read/write parquet files
  - scipy # use integration routine
  - ipython>=7.8.0 # black[jupyter] requirement
  - tokenize-rt>=3.2.0 # black[jupyter] requirement
